# Generated by Django 5.2 on 2025-05-20 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CO', 'Consultation'), ('RE', 'Réunion'), ('AU', 'Audience'), ('ME', 'Médiation'), ('AT', 'Autre')], default='CO', max_length=2, verbose_name='type')),
                ('date_debut', models.DateTimeField(verbose_name='date de début')),
                ('date_fin', models.DateTimeField(verbose_name='date de fin')),
                ('lieu', models.CharField(default='Cabinet', max_length=200, verbose_name='lieu')),
                ('sujet', models.CharField(max_length=200, verbose_name='sujet')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('statut', models.CharField(choices=[('EA', 'En attente de validation'), ('PL', 'Planifié'), ('CO', 'Confirmé'), ('EC', 'En cours'), ('TE', 'Terminé'), ('AN', 'Annulé'), ('RE', 'Refusé')], default='EA', max_length=2, verbose_name='statut')),
                ('motif_refus', models.TextField(blank=True, verbose_name='motif de refus')),
                ('date_proposition', models.DateTimeField(blank=True, null=True, verbose_name='date proposée')),
                ('rappel_envoye', models.BooleanField(default=False, verbose_name='rappel envoyé')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de modification')),
                ('avocat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rendezvous', to=settings.AUTH_USER_MODEL, verbose_name='avocat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendezvous', to='clients.client', verbose_name='client')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='dossiers.dossier', verbose_name='dossier associé')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
                'ordering': ['date_debut'],
                'indexes': [models.Index(fields=['date_debut', 'date_fin'], name='rendezvous__date_de_f148fa_idx'), models.Index(fields=['statut'], name='rendezvous__statut_80dbef_idx')],
            },
        ),
    ]
