# Generated by Django 5.2 on 2025-05-20 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='DOS000000', help_text='Référence unique du dossier', max_length=20, unique=True, verbose_name='référence')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('statut', models.CharField(choices=[('EC', 'En cours'), ('EA', 'En attente'), ('TE', 'Terminé'), ('AR', 'Archivé')], default='EC', max_length=2, verbose_name='statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de modification')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='date de clôture')),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur le dossier', verbose_name='notes')),
                ('montant_facture', models.DecimalField(blank=True, decimal_places=2, help_text='Montant total facturé pour ce dossier', max_digits=10, null=True, verbose_name='montant facturé')),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_avocat', to=settings.AUTH_USER_MODEL, verbose_name='avocat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'dossier',
                'verbose_name_plural': 'dossiers',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['reference'], name='dossiers_do_referen_ae94ef_idx'), models.Index(fields=['statut'], name='dossiers_do_statut_d0dd4d_idx'), models.Index(fields=['client'], name='dossiers_do_client__4f1506_idx'), models.Index(fields=['avocat'], name='dossiers_do_avocat__ac1d7b_idx')],
            },
        ),
    ]
