# Generated by Django 5.2 on 2025-05-20 23:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame'), ('AUTRE', 'Autre')], default='M', max_length=5, verbose_name='civilité')),
                ('type_client', models.CharField(choices=[('PAR', 'Particulier'), ('ENT', 'Entreprise'), ('ASS', 'Association')], default='PAR', max_length=3, verbose_name='type de client')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='prénom')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format: "+999999999". Maximum 15 chiffres autorisés.', regex='^\\+?1?\\d{9,15}$')], verbose_name='téléphone')),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format: "+999999999". Maximum 15 chiffres autorisés.', regex='^\\+?1?\\d{9,15}$')], verbose_name='téléphone secondaire')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('pays', models.CharField(default='Maroc', max_length=100, verbose_name='pays')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, verbose_name='lieu de naissance')),
                ('nationalite', models.CharField(default='Marocaine', max_length=100, verbose_name='nationalité')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='profession')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='raison sociale')),
                ('numero_rc', models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='numéro RC')),
                ('ice', models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='ICE')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom'], name='client_nom_idx'), models.Index(fields=['prenom'], name='client_prenom_idx'), models.Index(fields=['email'], name='client_email_idx'), models.Index(fields=['type_client'], name='client_type_idx')],
            },
        ),
    ]
