# Generated by Django 5.0.2 on 2025-05-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='barreau',
            field=models.CharField(blank=True, max_length=100, verbose_name='barreau'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='code postal'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_prestation_serment',
            field=models.DateField(blank=True, null=True, verbose_name='date de prestation de serment'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='departement',
            field=models.CharField(blank=True, max_length=100, verbose_name='département'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='numero_avocat',
            field=models.CharField(blank=True, max_length=50, verbose_name="numéro d'avocat"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pays',
            field=models.CharField(default='Maroc', max_length=100, verbose_name='pays'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/photos/', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='poste',
            field=models.CharField(blank=True, max_length=100, verbose_name='poste'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone_mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='téléphone mobile'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='ville'),
        ),
    ]
