# Generated by Django 5.0.2 on 2025-05-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_adresse_utilisateur_barreau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.ImageField(help_text='Une image représentative pour cette catégorie de droit', upload_to='law_categories/', verbose_name='icône')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage", verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'catégorie de droit',
                'verbose_name_plural': 'catégories de droit',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('avocat', 'Avocat'), ('secretaire', 'Secrétaire'), ('client', 'Client')], default='client', max_length=20, verbose_name='rôle'),
        ),
    ]
