# Generated by Django 5.2 on 2025-05-20 23:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='référence')),
                ('type_document', models.CharField(choices=[('CO', 'Contrat'), ('JU', 'Jugement'), ('RE', 'Requête'), ('ME', 'Mémoire'), ('PI', 'Pièce'), ('CR', 'Correspondance'), ('FA', 'Facture'), ('AU', 'Autre')], default='AU', max_length=2, verbose_name='type de document')),
                ('statut', models.CharField(choices=[('BR', 'Brouillon'), ('RE', 'En révision'), ('VA', 'Validé'), ('AR', 'Archivé')], default='BR', max_length=2, verbose_name='statut')),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt'])], verbose_name='fichier')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de modification')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('mots_cles', models.CharField(blank=True, max_length=200, verbose_name='mots-clés')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('confidentiel', models.BooleanField(default=False, verbose_name='confidentiel')),
                ('taille_fichier', models.PositiveIntegerField(editable=False, null=True, verbose_name='taille du fichier')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_crees', to=settings.AUTH_USER_MODEL, verbose_name='créateur')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='dossiers.dossier', verbose_name='dossier')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='validateur')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/versions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt'])], verbose_name='fichier')),
                ('numero_version', models.PositiveIntegerField(verbose_name='numéro de version')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('taille_fichier', models.PositiveIntegerField(editable=False, null=True, verbose_name='taille du fichier')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='créateur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'version du document',
                'verbose_name_plural': 'versions du document',
                'ordering': ['-numero_version'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['reference'], name='documents_d_referen_a458fb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type_document', 'statut'], name='documents_d_type_do_5c7f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['date_creation'], name='documents_d_date_cr_eb01c9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'numero_version'], name='documents_d_documen_e3196b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'numero_version')},
        ),
    ]
