# Generated by Django 5.0.2 on 2025-05-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RDV', 'Rendez-vous'), ('DOC', 'Document'), ('DOS', 'Dossier'), ('SYS', 'Système')], default='SYS', max_length=3, verbose_name='type')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='date de lecture')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
